Name: David Fastovich
Email: fastovich@wisc.edu

Loading required packages and reading data to be processed later
```{r}
require("png")
require("parallel")

vg <- readPNG("Van_Gogh.png")

red.vg <- vg[,,1]
green.vg <- vg[,,2]
blue.vg <- vg[,,3]
```

Filtering function
```{r}
par.chan.filtering <- function(x, k) {
  vg <- readPNG(x)
  dim.x <- dim(vg)
  # filtered.array <- array(data = c(numeric(), numeric(), numeric()), dim = c(dim.x[1],dim.x[2],dim.x[3]))
  filtered.list <- list()
  for (i in 1:3) {
    dim.y <- dim(vg[,,i])
    pad.X <- matrix(0, (dim.y[1]+2*k), (dim.y[2]+2*k))
    pad.X[(k+1):(dim.y[1]+k), (k+1):(dim.y[2]+k)] <- vg[,,i]
    filtered.mat <- matrix(0, dim(pad.X)[1], dim(pad.X)[2])
    for(row in (k+1):(dim.y[1]+k)) {
      for(col in (k+1):(dim.y[2]+k)) {
        filtered.mat[row, col] <- mean(pad.X[(row-k):(row+k),(col-k):(col+k)])
      }
    }
    unpadded.mat <- filtered.mat[seq_len(dim.x[1]) + k, seq_len(dim.x[2]) + k]
    
    filtered.list[[i]] <- unpadded.mat
    # filtered.array[,,i] <- unpadded.mat
  }
  # pad.X <- matrix(0, (dim.x[1]+2*k), (dim.x[2]+2*k))
  # pad.X[(k+1):(dim.x[1]+k), (k+1):(dim.x[2]+k)] <- x
  # filtered.mat <- matrix(0, dim(pad.X)[1], dim(pad.X)[2])
  # for(row in (k+1):(dim.x[1]+k)) {
  #   for(col in (k+1):(dim.x[2]+k)) {
  #     filtered.mat[row, col] <- mean(pad.X[(row-k):(row+k),(col-k):(col+k)])
  #   }
  # }
  # unpadded.mat <- filtered.mat[seq_len(dim.x[1]) + k, seq_len(dim.x[2]) + k]
  print("I keep on looping 1")
  # return(unpadded.mat)
  return(filtered.list)
}
```

Have to make one function that can be applied in parallel
```{r}
filter.image <- function(x, k, dim.x) {
  filtered.array <- array(data = c(numeric(), numeric(), numeric()), dim = c(dim.x[1],dim.x[2],dim.x[3]))
  for (i in 1:3) {
    filtered.array[,,i] <- par.chan.filtering(vg[,,i][1], k = k, dim.x = dim(vg[,,i]))
  }
  return(filtered.array)
}
  
```

Implementing function on Madison.png using 3 cores
```{r}
n.cores <- detectCores()
cluster <- makePSOCKcluster(names=n.cores)
clusterEvalQ(cl = cluster, expr = require(png))
# red.filtered <-  parLapply(cl = cluster, red.vg[1], fun = par.chan.filtering, k = 5, dim.x = dim(red.vg))
# green.filtered <-  parLapply(cl = cluster, x = green.vg[1], fun = par.chan.filtering, k = 5, dim.x = dim(green.vg))
# system.time(blue.filtered <-  parLapply(cl = cluster, blue.vg[1], fun = par.chan.filtering, k = 5, dim.x = dim(blue.vg)))
# system.time(filtered.array <- parLapply(cl = cluster, vg[1], fun = filter.image, k = 1, dim.x = dim(vg)))
filtered.list.1 <-  parLapply(cl = cluster, "Van_Gogh.png", par.chan.filtering, k = 1)
filtered.list.3 <-  parLapply(cl = cluster, "Van_Gogh.png", par.chan.filtering, k = 3)
filtered.list.5 <-  parLapply(cl = cluster, "Van_Gogh.png", par.chan.filtering, k = 5)
filtered.array.1 <- array(data = c(filtered.list.1[[1]][[1]], filtered.list.1[[1]][[2]], filtered.list.1[[1]][[3]]), dim = c(374, 800, 3))
filtered.array.3 <- array(data = c(filtered.list.3[[1]][[1]], filtered.list.3[[1]][[2]], filtered.list.3[[1]][[3]]), dim = c(374, 800, 3))
filtered.array.5 <- array(data = c(filtered.list.5[[1]][[1]], filtered.list.5[[1]][[2]], filtered.list.5[[1]][[3]]), dim = c(374, 800, 3))
writePNG(filtered.array.1, "fastovich_1.png")
writePNG(filtered.array.3, "fastovich_3.png")
writePNG(filtered.array.5, "fastovich_5.png")
```